### ISSUE TITLE
[Easy][Hacktoberfest] Update Design

### ISSUE THREAD

**Issue by TiagoDanin** [TiagoDanin/JUnicodeInfo#1]
![image](https://user-images.githubusercontent.com/5731176/46348787-83f92400-c626-11e8-87c2-3d01669a6196.png)
Problem with current: 
- Ugly
- Small letters

------

- index.html is automatically generated by CuboHub, use the iframe.html
- [iframe.html](https://github.com/TiagoDanin/JUnicodeInfo/blob/master/iframe.html)
- [UiKit Docs](https://getuikit.com/docs/)

[My other projects - #Hacktoberfest](https://github.com/search?q=label%3Ahacktoberfest+state%3Aopen+type%3Aissue+user%3ATiagoDanin&type=Issues)

**Comment by rangita01** [comment]
Hello, I would love to work on this.

**Comment by samslow** [comment]
wow i want fix that ugly list arrange

**Comment by lkoeln** [comment]
hey, I'd like to help :)

**Comment by TiagoDanin** [comment]
Resolved #5
